[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback so /proposal/:id works client-side
[[redirects]]
  from = "/api/*"
  to = "https://SEU-BACKEND-PROD.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


